--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 25-Mar-21 3:26:54 PM
-- Server version: 5.5.5-10.4.18-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE misa_eshop_develop;

--
-- Drop procedure `Proc_DeleteProduct`
--
DROP PROCEDURE IF EXISTS Proc_DeleteProduct;

--
-- Drop procedure `Proc_GenProductSKU`
--
DROP PROCEDURE IF EXISTS Proc_GenProductSKU;

--
-- Drop procedure `Proc_GetAllProduct`
--
DROP PROCEDURE IF EXISTS Proc_GetAllProduct;

--
-- Drop procedure `Proc_GetAllProductChildren`
--
DROP PROCEDURE IF EXISTS Proc_GetAllProductChildren;

--
-- Drop procedure `Proc_GetAllProductParent`
--
DROP PROCEDURE IF EXISTS Proc_GetAllProductParent;

--
-- Drop procedure `Proc_GetLength`
--
DROP PROCEDURE IF EXISTS Proc_GetLength;

--
-- Drop procedure `Proc_GetNumberOfRowProduct`
--
DROP PROCEDURE IF EXISTS Proc_GetNumberOfRowProduct;

--
-- Drop procedure `Proc_InsertProduct`
--
DROP PROCEDURE IF EXISTS Proc_InsertProduct;

--
-- Drop function `Func_GetPath`
--
DROP FUNCTION IF EXISTS Func_GetPath;

--
-- Drop procedure `Proc_GetPath`
--
DROP PROCEDURE IF EXISTS Proc_GetPath;

--
-- Drop procedure `Proc_GetProductByID`
--
DROP PROCEDURE IF EXISTS Proc_GetProductByID;

--
-- Drop procedure `Proc_GetProductByIDParent`
--
DROP PROCEDURE IF EXISTS Proc_GetProductByIDParent;

--
-- Drop procedure `Proc_GetProductBySKU`
--
DROP PROCEDURE IF EXISTS Proc_GetProductBySKU;

--
-- Drop procedure `Proc_GetProductPaging`
--
DROP PROCEDURE IF EXISTS Proc_GetProductPaging;

--
-- Drop procedure `Proc_UpdateProduct`
--
DROP PROCEDURE IF EXISTS Proc_UpdateProduct;

--
-- Drop table `product`
--
DROP TABLE IF EXISTS product;

--
-- Set default database
--
USE misa_eshop_develop;

--
-- Create table `product`
--
CREATE TABLE product (
  ProductID char(36) NOT NULL COMMENT 'Khóa chính',
  ProductName varchar(255) NOT NULL COMMENT 'Tên hàng hóa',
  SKU varchar(255) DEFAULT NULL COMMENT 'Mã hàng hóa',
  Status int(2) DEFAULT NULL COMMENT 'Trạng thái bán hàng 1- đang kinh doanh, 0-ngừng kinh doanh',
  CategoryCode int(11) DEFAULT NULL COMMENT 'Mã nhóm hàng hóa( từ 1-11)',
  BuyPrice double DEFAULT NULL COMMENT 'Giá mua',
  SellPrice double DEFAULT NULL COMMENT 'Giá bán',
  UnitCode int(11) DEFAULT NULL COMMENT 'Mã đơn vị (1- đôi, 2- chiếc, 3- túi, 4- kg, 5- thùng, 6-met, 7- cuộn, 8-lit)',
  IsShow int(2) DEFAULT NULL COMMENT 'Hiển thị trên màn hình bán hàng 1 - có hiển thị, 0- không hiển thị',
  Description varchar(4000) DEFAULT NULL COMMENT 'Mô tả',
  Image varchar(255) DEFAULT NULL,
  Color varchar(255) DEFAULT NULL COMMENT 'Màu sắc',
  Barcode int(11) DEFAULT NULL COMMENT 'mã vạch',
  FullPath varchar(255) DEFAULT NULL,
  ProductIDParent char(36) NOT NULL DEFAULT '' COMMENT 'ID của hàng hóa cha',
  CreatedBy varchar(255) DEFAULT 'vtt',
  CreatedDate datetime DEFAULT CURRENT_TIMESTAMP() COMMENT 'Ngày tạo',
  ModifiedDate datetime DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ProductID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1445,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `Barcode` on table `product`
--
ALTER TABLE product
ADD UNIQUE INDEX Barcode (Barcode);

DELIMITER $$

--
-- Create procedure `Proc_UpdateProduct`
--
CREATE PROCEDURE Proc_UpdateProduct (IN productID char(36), IN productName varchar(255), IN sku varchar(255), IN status int(2), IN categoryCode int(2), IN buyPrice double, IN sellPrice double, IN unitCode int(11), IN isShow int(2), IN description mediumtext, IN image mediumtext, IN barCode int(11), IN color varchar(255), IN modifiedDate datetime)
SQL SECURITY INVOKER
COMMENT 'Proc chỉnh sửa thông tin hàng hóa'
BEGIN
  UPDATE product p
  SET p.ProductName = productName,
      p.SKU = sku,
      p.Status = status,
      p.CategoryCode = categoryCode,
      p.BuyPrice = buyPrice,
      p.SellPrice = sellPrice,
      p.UnitCode = unitCode,
      p.IsShow = isShow,
      p.Description = description,
      p.Image = image,
      p.Barcode = barCode,
      p.Color = color,
      p.ModifiedDate = NOW()

  WHERE p.ProductID = productID;
END
$$

--
-- Create procedure `Proc_GetProductPaging`
--
CREATE PROCEDURE Proc_GetProductPaging (IN `limit` int, IN offset int, IN productName varchar(255), IN productSKU varchar(255), IN categoryCode int(11), IN unitCode int(2), IN sellPrice double, IN isShow int(2), IN status int(2))
SQL SECURITY INVOKER
COMMENT 'proc lấy phân trang kèm tìm kiếm những hàng hóa cha ở màn hình chính'
BEGIN
  SET productName = CASE WHEN productName IS NULL THEN '' ELSE productName END;
  SET productSKU = CASE WHEN productSKU IS NULL THEN '' ELSE productSKU END;

  SELECT
    *
  FROM product p
  WHERE p.ProductName LIKE CONCAT('%', productName, '%')
  AND p.SKU LIKE CONCAT('%', productSKU, '%')
  AND (CASE WHEN status IN (0, 1) THEN (p.Status = status) ELSE (TRUE) END)
  AND (CASE WHEN isShow IN (0, 1) THEN (p.IsShow = isShow) ELSE (TRUE) END)
  AND (CASE WHEN sellPrice > 0 THEN (p.SellPrice >= sellPrice) ELSE (TRUE) END)
  AND (CASE WHEN categoryCode > 0 THEN (p.CategoryCode = categoryCode) ELSE (TRUE) END)
  AND (CASE WHEN unitCode > 0 THEN (p.UnitCode = unitCode) ELSE (TRUE) END)
  AND p.ProductIDParent = '00000000-0000-0000-0000-000000000000'
  ORDER BY p.SKU ASC
  LIMIT `offset`, `limit`;

END
$$

--
-- Create procedure `Proc_GetProductBySKU`
--
CREATE PROCEDURE Proc_GetProductBySKU (IN SKU varchar(255))
SQL SECURITY INVOKER
COMMENT 'Lấy cửa hàng theo mã SKU'
BEGIN
  SELECT
    *
  FROM product p
  WHERE p.SKU = SKU;
END
$$

--
-- Create procedure `Proc_GetProductByIDParent`
--
CREATE PROCEDURE Proc_GetProductByIDParent (IN id char(36))
SQL SECURITY INVOKER
COMMENT 'Lấy danh sách hàng hóa con theo id hàng hóa cha'
BEGIN
  SELECT
    *
  FROM product p
  WHERE p.ProductIDParent = id;
END
$$

--
-- Create procedure `Proc_GetProductByID`
--
CREATE PROCEDURE Proc_GetProductByID (IN id char(36))
SQL SECURITY INVOKER
COMMENT 'Proc Lấy hàng hóa theo id'
BEGIN
  SELECT
    *
  FROM product p
  WHERE p.ProductID = id;
END
$$

--
-- Create procedure `Proc_GetPath`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetPath (IN cat_id char(36), OUT path text)
BEGIN
  DECLARE catname varchar(1000);/*tên để nối*/
  DECLARE temppath text;/*đường dẫn tên rỗng*/
  DECLARE tempparent char(36);/*id cha rỗng*/
  SET max_sp_recursion_depth = 4000;/*max nhập*/
  SELECT
    p.ProductName,
    p.ProductIDParent
  FROM product p
  WHERE p.ProductID = cat_id INTO catname, tempparent;/*catname = name, tempparent = parent*/
  IF tempparent = '00000000-0000-0000-0000-000000000000'/*Nếu tempparent null*/
  THEN
    SET path = catname;/* thì đường dẫn bằng catname tức tên cha to nhất*/
  ELSE/* Nếu như có cha, thức thằng catname đang chọn là con*/
    CALL Proc_GetPath(tempparent, temppath);/*đệ quy gọi lại với tempparent và path rỗng mới*/
    SET path = CONCAT(temppath, '--> ', catname);/* đường dẫn bằng nối đường dẫn cũ/tên thằng mới*/
  END IF;
END
$$

--
-- Create function `Func_GetPath`
--
CREATE DEFINER = 'root'@'localhost'
FUNCTION Func_GetPath (cat_id char(36))
RETURNS text CHARSET utf8mb4
DETERMINISTIC
BEGIN
  DECLARE res text;
  CALL Proc_GetPath(cat_id, res);/*gọi proceduce*/
  RETURN res;
END
$$

--
-- Create procedure `Proc_InsertProduct`
--
CREATE PROCEDURE Proc_InsertProduct (IN productID char(36), IN productName varchar(255), IN sku varchar(255), IN status int(2), IN categoryCode int(2), IN buyPrice double, IN sellPrice double, IN unitCode int(11), IN isShow int(2), IN description mediumtext, IN image mediumtext, IN barCode int(11), IN color varchar(255), IN modifiedDate datetime, IN productIDParent char(36))
SQL SECURITY INVOKER
COMMENT 'Proc thêm mới hàng hóa'
BEGIN
  DECLARE fullPath varchar(255);

  INSERT INTO product (ProductID, ProductName, SKU, Status, CategoryCode, BuyPrice, SellPrice, UnitCode, IsShow, Description, Image, CreatedDate, CreatedBy, ModifiedDate, ProductIDParent, Color, Barcode, FullPath)
    VALUES (productID, productName, sku, status, categoryCode, buyPrice, sellPrice, unitCode, isShow, description, image, NOW(), 'vtt', NOW(), productIDParent, color, barCode, fullPath);
  SET fullPath = Func_GetPath(productID);
  UPDATE product p
  SET p.FullPath = Func_GetPath(productID)
  WHERE p.ProductID = productID;
END
$$

--
-- Create procedure `Proc_GetNumberOfRowProduct`
--
CREATE PROCEDURE Proc_GetNumberOfRowProduct ()
SQL SECURITY INVOKER
COMMENT 'Lấy số lượng bản ghi của bảng Product'
BEGIN
  SELECT
    COUNT(*)
  FROM product p;
END
$$

--
-- Create procedure `Proc_GetLength`
--
CREATE PROCEDURE Proc_GetLength (IN productName varchar(255), IN productSKU varchar(255), IN categoryCode int(11), IN unitCode int(2), IN sellPrice double, IN isShow int(2), IN status int(2))
SQL SECURITY INVOKER
COMMENT 'Proc lấy số bản ghi cha thỏa mãn điều kiện search'
BEGIN
  SET productName = CASE WHEN productName IS NULL THEN '' ELSE productName END;
  SET productSKU = CASE WHEN productSKU IS NULL THEN '' ELSE productSKU END;

  SELECT
    COUNT(*) AS NumberOfRecord
  FROM product p
  WHERE p.ProductName LIKE CONCAT('%', productName, '%')
  AND p.SKU LIKE CONCAT('%', productSKU, '%')
  AND (CASE WHEN status IN (0, 1) THEN (p.Status = status) ELSE (TRUE) END)
  AND (CASE WHEN isShow IN (0, 1) THEN (p.IsShow = isShow) ELSE (TRUE) END)
  AND (CASE WHEN sellPrice > 0 THEN (p.SellPrice >= sellPrice) ELSE (TRUE) END)
  AND (CASE WHEN categoryCode > 0 THEN (p.CategoryCode = categoryCode) ELSE (TRUE) END)
  AND (CASE WHEN unitCode > 0 THEN (p.UnitCode = unitCode) ELSE (TRUE) END)
  AND p.ProductIDParent = '00000000-0000-0000-0000-000000000000';
END
$$

--
-- Create procedure `Proc_GetAllProductParent`
--
CREATE PROCEDURE Proc_GetAllProductParent ()
SQL SECURITY INVOKER
COMMENT 'Proc lấy hàng hóa cha'
BEGIN
  SELECT
    *
  FROM product p
  WHERE p.ProductIDParent = '00000000-0000-0000-0000-000000000000';
END
$$

--
-- Create procedure `Proc_GetAllProductChildren`
--
CREATE PROCEDURE Proc_GetAllProductChildren (IN id char(36))
SQL SECURITY INVOKER
COMMENT 'proc lấy hàng hóa con ở bảng chi tiết thuộc tính'
BEGIN
  SELECT
    *
  FROM product p
  WHERE p.ProductIDParent = id;
END
$$

--
-- Create procedure `Proc_GetAllProduct`
--
CREATE PROCEDURE Proc_GetAllProduct ()
SQL SECURITY INVOKER
COMMENT 'Lấy tất cả hàng hóa'
BEGIN
  SELECT
    *
  FROM product p;
END
$$

--
-- Create procedure `Proc_GenProductSKU`
--
CREATE PROCEDURE Proc_GenProductSKU (IN productKey varchar(255))
SQL SECURITY INVOKER
COMMENT 'Tạo mới mã sku cho sản phẩm'
BEGIN
  DECLARE productSkuCode varchar(255);
  DECLARE codeNumber int(11);

  SELECT
    p.SKU INTO productSkuCode
  FROM product p
  WHERE p.SKU LIKE CONCAT(CONVERT(productKey, binary), '%')
  AND CAST(SUBSTR(p.SKU, LENGTH(productKey) + 1) AS int) > 0
  ORDER BY p.SKU DESC
  LIMIT 1;

  SET codeNumber = CASE WHEN productSkuCode IS NULL THEN 1 ELSE CAST(SUBSTR(productSkuCode, LENGTH(productKey) + 1) AS int) + 1 END;

  SELECT
    CONCAT(productKey, codeNumber);

END
$$

--
-- Create procedure `Proc_DeleteProduct`
--
CREATE PROCEDURE Proc_DeleteProduct (IN id char(36))
SQL SECURITY INVOKER
COMMENT 'Proc xóa hàng hóa cha ở bảng chính'
BEGIN
  DELETE
    FROM product
  WHERE ProductID = id
    OR ProductIDParent = id;
END
$$

DELIMITER ;

-- 
-- Dumping data for table product
--
INSERT INTO product VALUES
('026a265f-fd8b-4603-9db5-4dd58a184e5e', 'Đồng hồ Rolex', 'DHR1', 1, 3, 200000000, 250000000, 2, 0, 'Đồng hồ cho nhà giàu vkl', NULL, NULL, NULL, 'Đồng hồ Rolex', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-20 13:53:52', '2021-03-20 13:54:32'),
('072cc770-6265-48b4-b6de-6b78460b0ea1', 'Bata Trắng', 'BT1', 1, 8, 70000, 90000, 1, 1, 'Không có', NULL, NULL, NULL, 'Bata Trắng', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 09:59:32', '2021-03-22 09:59:32'),
('09299cbf-a4b4-4b95-92e0-1ef7790daea0', 'Áo khoác ( đen )', 'AK1-DE1', 1, NULL, 200000, 300000, NULL, NULL, NULL, NULL, 'đen', NULL, 'Áo khoác--> Áo khoác ( đen )', '238b8143-54d4-4123-a0dd-64b69d56b1d9', 'vtt', '2021-03-25 08:02:21', '2021-03-25 08:02:21'),
('0a72ce45-e97f-46b2-bd8c-618c58250326', 'Quần đùi', 'QD1', 1, 12, 50000, 55000, 2, 1, 'Quần ba sọc', NULL, NULL, NULL, 'Quần đùi', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-20 12:34:43', '2021-03-20 12:34:43'),
('0d7ef49c-2614-4160-909e-81d86d93f8c1', 'Đồ dùng cá nhân', 'DDCN6', 1, 1, 338493263, 240000, 1, 0, 'Animi minus architecto soluta accusamus dolore fugit dolore sunt quod. Veritatis eaque sit fugiat similique. Natus asperiores omnis ratione et blanditiis officiis id accusantium ducimus minima doloremque labore dicta consequatur. Quo distinctio et labore voluptates; dicta temporibus et quaerat et. Maxime iusto sed excepturi error; sed fuga animi voluptatem non.', '4M46S3B', NULL, NULL, 'Đồ dùng cá nhân', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-24 23:28:50', '2021-03-24 23:28:50'),
('0f8cfd75-6742-4487-9c94-7b267ab96297', 'Xe máy Honda', 'XMH1', 1, 14, 90000000, 150000000, 1, 1, 'Xe máy đắt tiền cho nhà giàu Test sửa 1111', 'link:///', 'Đỏ', 17021041, 'Xe máy--> Xe máy--> Xe máy Honda', '7623d42f-35f4-1ce5-987d-e8c757976496', 'vtt', '2021-03-18 10:34:16', '2021-03-24 21:08:51'),
('11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Hoa quả ', 'HQ1', 0, 9, 158534, 341711, 3, 1, 'A reprehenderit expedita officia consequatur. A autem molestias tempore qui.\r\nBlanditiis quos non error dignissimos. Modi sequi maiores nihil dolores. Voluptatem porro sit quia error. Animi delectus tenetur consequatur libero! Consequatur sit totam nihil quae. Possimus et aut sint sed? Autem qui sit ad nesciunt; nulla natus quos consequatur aliquam.\r\n', '102E0EV1F47A95B5BNIL10U9M517OUT7P4O59X7M', NULL, 307297987, 'Hoa quả ', '00000000-0000-0000-0000-000000000000', 'Adolph Francisco', '2000-12-28 15:52:12', '2021-03-22 09:56:22'),
('11f7089b-33e6-371a-f817-7000f455f3d5', 'Giày ', 'G1', 1, 4, 862948515, 469947961, 2, 0, 'Vero totam inventore distinctio sunt. Dolorem voluptatem molestias non nostrum. Velit voluptatem distinctio delectus dolorem. Laborum quos ipsam ut provident. Atque esse omnis et repellat.\r\nAsperiores beatae unde illo voluptatem. In tempora sequi et sint! Eum voluptatem ut nemo illo. Dolorem atque ipsum explicabo dolore! Asperiores rem qui accusantium fuga.\r\n', 'FF3K860BJXL8', '0', 1632497363, 'Giày ', '00000000-0000-0000-0000-000000000000', 'Kasey Furr', '2002-09-29 02:55:38', '1976-05-12 14:39:22'),
('142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nước ngọt ', 'NN1', 0, 11, 432, 200000, 4, 1, 'Enim ullam fugiat sunt et dolore molestiae omnis nihil sit atque aliquid nobis necessitatibus a.', 'WCC04WA7S7', NULL, 2147483647, 'Nước ngọt ', '00000000-0000-0000-0000-000000000000', 'Letha Bolt', '1999-01-01 00:07:13', '1970-01-01 00:00:04'),
('17120d02-6ab5-3e43-18cb-66948daf6128', 'Giường', 'DGD1', 0, 2, 79113585, 118561606, 1, 1, 'Ipsa sint fugit fuga soluta; aut dolorem at rerum qui impedit; dolor qui cupiditate, expedita quia inventore veniam architecto voluptatem nihil culpa dolorem qui recusandae.\r\nDolorem alias sit et quae, ut natus accusantium omnis exercitationem enim corporis qui omnis. Officia veritatis, consectetur repellendus nisi incidunt debitis omnis quia omnis iste.', 'PU77823H9ANM99OGB57T081J041U61', NULL, 1837520715, 'Giường', '00000000-0000-0000-0000-000000000000', 'Miyoko Mckinney', '2012-06-02 17:57:52', '2021-03-22 09:55:51'),
('18159baf-9feb-4f52-a10f-77ec4e37abd5', 'Chổi lau nhà', 'CLN1', 1, 2, 30000, 40000, 2, 1, 'test short key', NULL, NULL, NULL, 'Chổi lau nhà', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-25 13:40:08', '2021-03-25 13:40:08'),
('1c9d8561-ca23-4d15-9818-0aff31eeff3d', 'Áo lót nữ', 'AL2', 1, 15, 100000, 200000, 1, 1, 'Áo lót ren', NULL, NULL, NULL, 'Áo lót nữ', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-20 12:38:10', '2021-03-22 11:22:18'),
('1ded3dd7-32db-5bc9-9190-67245e8b283e', 'Đồng hồ ', 'DH1', 0, 3, 82, 50000, 1, 0, 'Numquam nemo omnis quas aut. Qui et non harum deleniti? Sint eveniet ut maxime omnis. Velit libero qui in rem. Similique tempora praesentium quas quis? Rem aliquam consequatur placeat et. Unde repellendus delectus id corporis. Omnis sapiente atque voluptas fuga. Suscipit et inventore earum dolore!\r\nAlias dolorum error distinctio eos.', '2BU14OD317TT5WHV8M158VLMMMR9CMQ45V07C276386A8QFR84AX9VZ977W7P3MJF68W4CGXAQ5KUB5', NULL, 829697213, 'Đồng hồ ', '00000000-0000-0000-0000-000000000000', 'Gayle Baugh', '1999-01-01 00:01:23', '1970-01-01 00:57:34'),
('1f74cd3f-6de4-5324-0180-e8e2a817c80e', 'Giày ', 'G2', 0, 4, 610409, 798350, 2, 0, 'Totam facilis similique possimus natus; excepturi sit praesentium quasi similique. Commodi sunt placeat cupiditate quisquam? Recusandae rerum at explicabo qui! Cupiditate magni iure et rem. Iusto corrupti dolorem aliquid voluptatem. Magnam adipisci pariatur sed ut. Ut numquam doloremque velit temporibus. Est illo reprehenderit ea quos! Ipsa ratione error est natus.', 'S7U1LCSGK2CH698W937ISU648FJ9AGBQ7GY16Y4', NULL, 307297988, 'Giày ', '00000000-0000-0000-0000-000000000000', 'Adah Jameson', '2017-10-01 16:44:23', '2021-03-23 11:15:07'),
('22fc7048-fbc5-4987-8bf9-1a4249a58c20', 'Dầu ăn', 'DA2', 1, 2, 30000, 56000, 8, 1, 'Dầu ăn giá rẻ', NULL, NULL, NULL, 'Dầu ăn', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 11:04:27', '2021-03-22 11:04:27'),
('238b8143-54d4-4123-a0dd-64b69d56b1d9', 'Áo khoác', 'AK1', 1, 15, 200000, 300000, 0, 1, NULL, NULL, NULL, NULL, 'Áo khoác', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-24 13:56:19', '2021-03-25 08:02:21'),
('24629593-3d34-32fd-997d-e8c757976496', 'Váy', 'V1', 1, 13, 97, 6000000, 1, 1, 'Quaerat neque quae qui non; beatae culpa molestiae nulla quibusdam? Ipsa nobis quia voluptatibus consequatur; repellendus adipisci sint quod ad. Consectetur voluptatem sed delectus consequatur; nihil molestiae iusto quas eum. Quis nesciunt dolorem earum est! Dolorem porro magnam ut quo; laborum dolorem totam ut adipisci.\r\nIpsum ullam nobis ratione a.\r\n', 'KBOCNBS', NULL, 614948849, 'Váy', '00000000-0000-0000-0000-000000000000', 'Melia Gates', '1999-01-01 00:01:38', '1971-06-17 07:53:58'),
('25073210-2818-4817-944f-418970898609', 'Giày da đen', 'GDD1', 0, 6, 200000, 300000, 1, 1, NULL, NULL, NULL, NULL, 'Giày da đen', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-25 09:33:48', '2021-03-25 09:34:20'),
('284ccb05-337b-7e6f-9090-67245e8b283e', 'Váy', 'V2', 0, 13, 941, 4500000, 1, 1, 'Natus nulla nemo error alias. Laborum ut sit quas aut. Possimus voluptate temporibus quidem et! Consequatur aut doloribus aut reprehenderit. Ut suscipit repellat obcaecati dolorum! Voluptates sit accusamus beatae quia? Asperiores repellat ut ullam ipsam! Assumenda magnam sed quibusdam quasi; assumenda iusto fugit error rerum? Eligendi et laudantium perspiciatis aliquid.\r\n', '0P0ZB1RJ8X54', 'PrincetonOrange', 829697212, 'Váy--> Váy', '24629593-3d34-32fd-997d-e8c757976496', 'Adam Maddox', '1999-01-01 00:15:42', '1978-06-16 09:25:41'),
('2dc75661-a348-4c6c-a8e9-3baa1833c4b8', 'Áo ( tim )', 'A2-TI1', 1, NULL, 500000, 600000, NULL, NULL, NULL, NULL, 'tim', NULL, 'Áo--> Áo ( tim )', '83f54006-2758-440c-85e6-a86faa47440a', 'vtt', '2021-03-24 22:33:27', '2021-03-25 08:09:24'),
('2dcedb9c-6c32-7d27-977d-e8c757976496', 'Đồ dùng cá nhân', 'DDCN1', 1, 1, 338493263, 240000, 1, 0, 'Animi minus architecto soluta accusamus dolore fugit dolore sunt quod. Veritatis eaque sit fugiat similique. Natus asperiores omnis ratione et blanditiis officiis id accusantium ducimus minima doloremque labore dicta consequatur. Quo distinctio et labore voluptates; dicta temporibus et quaerat et. Maxime iusto sed excepturi error; sed fuga animi voluptatem non.', '4M46S3B', NULL, 1043326479, 'Đồ dùng cá nhân', '00000000-0000-0000-0000-000000000000', 'Ariel Hermann', '2002-10-01 22:27:30', '2021-03-25 14:27:50'),
('2e9c2d0c-d90d-49b8-a4a0-f959972f9e9f', 'Giày ', 'G10', 1, 8, 200000, 500000, 0, 1, NULL, NULL, NULL, NULL, 'Giày ', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-25 09:08:31', '2021-03-25 09:08:31'),
('2fb0b105-7808-503a-76dd-867949feb8b5', 'Nước ngọt ', 'NN2', 0, 11, 982959394, 6000, 4, 0, 'Ducimus consequuntur quidem inventore dolore. Voluptas reiciendis ut in consectetur; et omnis ducimus nihil nesciunt. Nihil nobis id sit perspiciatis. Molestias illum eos similique itaque. In aut modi sit eligendi.\r\nQuasi asperiores nihil sequi et. Omnis voluptatem enim et perspiciatis! Mollitia ex qui voluptas ut. Id sit cumque qui dolores.', 'Q4T', NULL, 2052269079, 'Nước ngọt ', '00000000-0000-0000-0000-000000000000', 'Josephine Norwood', '2006-07-26 20:16:17', '1980-06-23 18:27:10'),
('307460fd-1492-469f-a7f5-0df4fae4edcf', 'Áo', 'A5', 1, 15, 500000, 600000, 2, 1, 'test them moi nhieu ban ghi 2', 'string', 'string', NULL, 'Áo', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-23 11:21:35', '2021-03-23 11:21:35'),
('31d94d01-de67-46ae-abaf-cc3cab89d7c1', 'Ban chai danh rang ( đỏ )', 'BCDR1-DO1', 1, NULL, 3815037, 6000000, NULL, NULL, NULL, NULL, 'đỏ', NULL, 'Ban chai danh rang--> Ban chai danh rang ( đỏ )', '4ed7648c-2e62-429f-b9d4-ff91394dc47b', 'vtt', '2021-03-25 08:13:24', '2021-03-25 08:14:40'),
('320690a3-9d97-422b-97c5-dd9e2628dbdf', 'Khăn tắm', 'KT2', 0, 10, 515483199, 63000, 1, 1, 'Esse perferendis dolor distinctio voluptas commodi consequatur sint consequatur adipisci voluptate voluptatem magnam error similique. Ut est velit accusantium sint laboriosam tempora et sunt similique iste, voluptatem ratione exercitationem! Omnis quo omnis commodi hic nesciunt magnam iure error iste perspiciatis ut iste quam. Voluptas ratione exercitationem perspiciatis ut; itaque est sit.', 'ROW2DRZ2005J', NULL, NULL, 'Khăn tắm', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 14:17:57', '2021-03-22 14:17:57'),
('3240ef0d-8a10-45bd-b14f-629b269c246e', 'Khăn tắm Trẻ Em', 'KTTE1', 0, 10, 515483199, 63000, 1, 1, 'Esse perferendis dolor distinctio voluptas commodi consequatur sint consequatur adipisci voluptate voluptatem magnam error similique. Ut est velit accusantium sint laboriosam tempora et sunt similique iste, voluptatem ratione exercitationem! Omnis quo omnis commodi hic nesciunt magnam iure error iste perspiciatis ut iste quam. Voluptas ratione exercitationem perspiciatis ut; itaque est sit.', 'ROW2DRZ2005J', NULL, NULL, 'Khăn tắm Trẻ Em', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 14:17:10', '2021-03-22 14:18:53'),
('3447f038-c84d-47e9-ad21-a4aa2f6e3dfb', 'xoong', 'X2', 0, 2, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, 'xoong', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-24 10:56:03', '2021-03-24 23:33:00'),
('3599ef50-13ed-5404-0e63-eeb1d8ed8cef', 'Đồ dùng cá nhân', 'DDCN6-B', 1, 1, 87, 100000, 1, 1, 'Quod dolor adipisci earum et; laboriosam voluptatem placeat nam aut; perferendis iste qui nesciunt asperiores. Eos quia natus quisquam ipsum. Nihil distinctio autem veniam culpa? Qui aut odit sit aliquam. Architecto excepturi alias repellendus saepe! Sit explicabo maxime nemo harum; laborum unde earum non at. Eos beatae perspiciatis error voluptatum;\r\n', '8VP26X', 'BabyPink', 614948848, 'Đồ dùng cá nhân--> Đồ dùng cá nhân', '2dcedb9c-6c32-7d27-977d-e8c757976496', 'Elli Robertson', '1999-01-01 00:01:28', '2021-03-25 14:27:50'),
('36cefeb6-4c78-464b-931a-ebcf255aaf13', 'Áo mưa trẻ em', 'AMTE1', 1, 15, 501000, 601000, 2, 0, 'Không có gì', NULL, NULL, NULL, 'Áo mưa trẻ em', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-20 12:29:12', '2021-03-20 12:40:38'),
('37060412-ba91-439e-a389-3b15bb2c5f1c', 'áo', 'A6', 1, 15, 100000, 500000, 5, 1, NULL, NULL, NULL, NULL, 'áo', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-23 23:30:21', '2021-03-24 08:33:15'),
('3760d71f-6e2f-5b32-19cb-6694bdaf6128', 'Giày da', 'GD1', 1, 6, 220000, 330000, 2, 1, 'Giày da phong cách', NULL, 'đen', 24562, 'Giày --> Giày da', '1f74cd3f-6de4-5324-0180-e8e2a817c80e', 'vtt', '2021-03-17 16:48:39', '2021-03-17 16:48:39'),
('398771b0-261e-48bf-8850-323c068f0ca8', 'Dầu ăn', 'DA1', 1, 2, 30000, 56000, 8, 1, 'Dầu ăn giá rẻ', NULL, NULL, NULL, 'Dầu ăn', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 09:55:02', '2021-03-22 09:55:02'),
('39d3817e-1a0e-4d44-868b-ca3845e370c2', 'Áo ( xanh )', 'A2-XA1', 1, NULL, 500000, 600000, NULL, NULL, NULL, NULL, 'xanh', NULL, 'Áo--> Áo ( xanh )', '83f54006-2758-440c-85e6-a86faa47440a', 'vtt', '2021-03-24 22:33:27', '2021-03-25 08:09:24'),
('3f1eb921-c341-40be-a896-d44a1df4239d', 'áo mưa ', 'AM4', 1, 15, 2000, 5000, 5, 1, NULL, NULL, NULL, NULL, 'áo mưa ', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-23 20:44:29', '2021-03-23 20:44:29'),
('404fe340-1fd3-414b-aadb-e5d54223c257', 'Giày vải', 'G3', 0, 8, 404512240, 8000, 2, 1, 'Eaque doloribus dicta corporis omnis accusamus vitae non. Magnam a hic similique fugiat! Animi quia eos non omnis; inventore et eius sit et; et corporis ipsam quos culpa. Unde magni fugit recusandae laudantium. Earum maiores eos magnam aut! Enim quo qui aliquam quibusdam? Ut aut odit ipsum error; numquam ratione et tempore corrupti.', 'GU2G0MM4OAUQI06ISX316J6DST11Y7VRR35IZ0FQ9K621K9846QJ2TYK', 'PrussianBlue', 1417748997, 'Giày --> Giày vải', '1f74cd3f-6de4-5324-0180-e8e2a817c80e', 'Delcie Abney', '2003-01-06 17:04:13', '1970-01-01 02:09:09'),
('411f78e1-48de-45b7-acb6-d2049356da8e', 'Giày Thượng Đình', 'GTD1', 1, 5, 30000, 70000, 1, 1, 'Giày rẻ ', NULL, NULL, NULL, 'Giày Thượng Đình', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 09:48:45', '2021-03-22 09:48:45'),
('450c8195-2d4c-46cc-90c0-8c6fecd25cf1', 'Áo lót nữ', 'ALN4', 1, 15, 100000, 200000, 1, 1, 'Áo lót ren', NULL, NULL, NULL, 'Áo lót nữ', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-23 17:46:46', '2021-03-23 17:46:46'),
('4577565a-7e3e-493a-74dd-867949feb8b5', 'Quần ', 'Q1', 1, 12, 137654331, 180000, 1, 0, 'Dicta inventore voluptatem dicta deserunt. Voluptatem voluptate asperiores consectetur blanditiis. Consequuntur dolorem quo et necessitatibus! Dolor minima amet adipisci sed. Temporibus perspiciatis unde quia maxime; quia dolores minima reprehenderit tenetur. Quia maxime et sit sed; perspiciatis quam sunt iure veritatis. Voluptas accusamus voluptatibus omnis corrupti. Exercitationem quia ut;', 'C75Z7903Q1P3RMQK', NULL, 1632497362, 'Quần ', '00000000-0000-0000-0000-000000000000', 'Felix Alba', '2007-01-17 16:42:08', '2018-10-07 19:37:35'),
('469b3ece-744a-45d5-957d-e8c757976496', 'Đồ dùng học tập', 'DDHT1', 1, 1, 826968319, 68725912, 1, 0, 'Et blanditiis minima ut odit id hic consequatur omnis quidem fugit minima. Iste et esse in laborum consectetur ut et vel molestiae quis architecto vel temporibus? Debitis molestias natus esse delectus. Est odio earum voluptatem eligendi obcaecati ab unde similique omnis voluptatem sit nisi ipsum suscipit.', '0', NULL, 307297986, 'Đồ dùng học tập', '00000000-0000-0000-0000-000000000000', 'Vanita Kelleher', '2013-07-11 20:51:56', '2021-03-23 21:01:58'),
('4760d61f-6e2f-5b32-19cb-66948daf6128', 'Khăn bông', 'KB1', 1, 10, 250000, 300000, 1, 1, NULL, NULL, 'đen', 1702, 'Khăn--> Khăn bông', '4760d71f-6e2f-5b32-19cb-66948daf6128', 'vtt', '2021-03-17 23:39:35', '2021-03-17 23:39:35'),
('4760d71f-6e2f-5b32-19cb-66948daf6128', 'Khăn', 'K1', 0, 10, 515483199, 63000, 1, 1, 'Esse perferendis dolor distinctio voluptas commodi consequatur sint consequatur adipisci voluptate voluptatem magnam error similique. Ut est velit accusantium sint laboriosam tempora et sunt similique iste, voluptatem ratione exercitationem! Omnis quo omnis commodi hic nesciunt magnam iure error iste perspiciatis ut iste quam. Voluptas ratione exercitationem perspiciatis ut; itaque est sit.', 'ROW2DRZ2005J', NULL, 829697211, 'Khăn', '00000000-0000-0000-0000-000000000000', 'Nathan Salisbury', '2007-04-25 08:42:04', '1970-01-01 00:10:39'),
('4760d71f-6e2f-5b32-19cb-6694bdaf6128', 'Khăn quàng cổ', 'KQC1', 1, 10, 20000, 30000, 1, 1, 'khăn quàng cổ học sinh', NULL, 'đen', 4562, 'Khăn--> Khăn quàng cổ', '4760d71f-6e2f-5b32-19cb-66948daf6128', 'vtt', '2021-03-17 15:53:57', '2021-03-17 15:53:57'),
('49be2a4a-95da-4b13-8a78-d6c4ccc51e52', 'Áo Dạ', 'AD', 1, 15, 500000, 600000, 2, 1, 'Áo dạ', NULL, NULL, NULL, 'Áo Dạ', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 16:05:59', '2021-03-22 16:05:59'),
('4d7b21db-2e02-12b7-a9db-e5d54223c257', 'Nước ngọt ', 'NN3', 1, 11, 513577678, 9000, 4, 1, 'Et voluptate, voluptatem fugit tenetur omnis tenetur dolorum rerum obcaecati magnam dolor laudantium dolor dolore.', '5D5K8HVZ764159Q1SU2117L42R0WF736HUY36OKBNTNBR0DTY', 'OxfordBlue', 614948847, 'Nước ngọt --> Nước ngọt ', '2fb0b105-7808-503a-76dd-867949feb8b5', 'Winnifred Brantley', '2006-12-10 05:22:26', '1999-10-21 05:42:49'),
('4ed7648c-2e62-429f-b9d4-ff91394dc47b', 'Bàn chải đánh răng', 'BCDR1', 1, 1, 3815037, 6000000, 5, 1, 'test them moi', NULL, 'LavenderPurple', 925, 'Ban chai danh rang', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-24 21:36:23', '2021-03-25 08:14:40'),
('52d303b9-e475-4246-9d6d-2a0f6bc3d3f9', 'áo mưa ', 'AM3', 1, 15, 2000, 5000, 5, 1, NULL, NULL, NULL, NULL, 'áo mưa ', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-23 08:55:02', '2021-03-23 22:03:45'),
('52d8a792-c917-40e2-bb15-fa262296b7a2', 'quan ( đen )', 'Q4-D', 1, NULL, 20000, 20000, NULL, NULL, NULL, NULL, 'đen', NULL, 'quan--> quan ( đen )', 'a7f2f7b5-c97c-408a-9353-6f4b721b3cf7', 'vtt', '2021-03-24 23:01:49', '2021-03-25 11:34:13'),
('551a2660-e828-4a65-8a38-425eb2467bda', 'áo', 'A7', 0, 15, 300000, 400000, 2, 1, NULL, NULL, NULL, NULL, 'áo', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-24 09:33:59', '2021-03-25 11:29:45'),
('5608f456-3b97-2e05-5d92-08c864661f9c', 'Nước ngọt ', 'NN4', 1, 11, 312, 15000, 4, 1, 'Velit ut eaque voluptas eveniet nulla et sit aut ut voluptate rerum quia. Odit natus omnis voluptatem consequatur et excepturi rerum nisi et illum! Voluptatem magnam maxime ducimus minima consectetur. Dolor iusto tempora, ut natus perspiciatis laborum totam beatae cumque exercitationem tempore minus pariatur necessitatibus.', 'A3T642GTLZ', NULL, 1258074845, 'Nước ngọt ', '00000000-0000-0000-0000-000000000000', 'Jerome Gipson', '1999-01-01 00:05:13', '1970-01-01 00:00:10'),
('5660d465-6020-48f3-75dd-867949feb8b5', 'Giày sneaker', 'G5', 0, 7, 446434411, 337797849, 2, 0, 'Vitae sequi sit ab soluta. Iste ut est id dolorum. Qui quis odio qui dolorum. Perspiciatis omnis nihil sit necessitatibus! Blanditiis qui nobis dolor vel. Dolorem error autem sint facilis! Libero aut illo exercitationem nam. Non facere recusandae et tempora. Qui eveniet omnis qui vel. Eveniet et quia saepe omnis.\r\n', '75I922893D25Z', 'Crimson', 2052269078, 'Giày --> Giày vải--> Giày sneaker', '404fe340-1fd3-414b-aadb-e5d54223c257', 'Laura Barger', '2011-05-23 17:42:46', '2007-12-24 13:40:16'),
('59d19422-6657-452e-a7db-e5d54223c257', 'Đồ dùng học tập', 'DDCN4', 0, 1, 63, 727689123, 1, 1, 'Laboriosam ut est porro sed. Voluptatem veritatis reiciendis iusto dicta. Doloribus distinctio perspiciatis autem velit! Enim saepe ex natus magnam; neque molestiae magnam aut voluptatem. Omnis nesciunt nostrum aut in. Dolore iste unde vel veritatis! Et cupiditate sunt omnis eligendi.\r\nNeque commodi modi blanditiis fugit. Amet vel assumenda enim velit!\r\n', 'R011HR8810360F607A', 'Cream', 92549622, 'Đồ dùng học tập--> Đồ dùng học tập', '469b3ece-744a-45d5-957d-e8c757976496', 'Denisha Mcginnis', '1999-01-01 00:01:04', '1978-08-30 04:07:51'),
('5ae2d70b-201d-3e23-7f32-6a1673ffca7c', 'Xe máy', 'XM1', 0, 14, 184601663, 20000000, 1, 1, 'Molestiae perspiciatis dicta nisi ut. Est expedita voluptas natus quam. Explicabo magni consequatur sed enim. In quia ut numquam ea? Numquam voluptates soluta natus facilis. Tempora perferendis blanditiis laudantium culpa? Suscipit quia voluptas iste consectetur! Fugiat sed est aut iste. Et expedita ut voluptas qui. Et unde voluptatum nostrum ut;\r\n', '5812N66M598N', NULL, 1837520717, 'Xe máy', '00000000-0000-0000-0000-000000000000', 'Gertie Abel', '2016-12-22 09:47:13', '1970-01-01 02:25:46'),
('5b2fcdf5-2050-7cb2-8f90-67245e8b283e', 'Giày bata', 'G6', 0, 5, 4, 33000, 2, 1, 'Facilis amet enim nihil enim. Sunt ab ut quo debitis; dolore aut quia rem aut. Unde quae architecto sed expedita! Autem qui vitae neque ut. Non rerum quisquam iusto et; sunt unde nostrum adipisci voluptatem. Quo laudantium odit sint expedita. Et eum nisi rerum quia. Dolores aspernatur veritatis placeat quasi.\r\n', '0YK98Y0TCG9S67X89G0N4C5YM0I6K31V0688', 'Cardinal', 1837520716, 'Giày --> Giày bata', '1f74cd3f-6de4-5324-0180-e8e2a817c80e', 'Burton Bunnell', '1999-01-01 00:00:05', '1970-01-01 00:56:40'),
('5e024ca3-a4f5-46ea-9757-701bce8dded7', 'Áo mưa', 'AM1', 1, 15, 500000, 700000, 2, 1, 'Áo mưa dùng một lần', 'string', 'string', 18991, 'Áo mưa', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-19 23:35:54', '2021-03-25 14:43:35'),
('604e0d9d-16ad-4e58-bd44-c542f9342b15', 'Ban chai danh rang ( đen )', 'BCDR1-DE1', 1, NULL, 3815037, 6000000, NULL, NULL, NULL, NULL, 'đen', NULL, 'Ban chai danh rang--> Ban chai danh rang ( đen )', '4ed7648c-2e62-429f-b9d4-ff91394dc47b', 'vtt', '2021-03-25 08:13:24', '2021-03-25 08:14:40'),
('61750a26-2412-4705-9e12-0fc01ca3dfc5', 'Quần', 'Q3', 0, 12, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, 'quan', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-24 10:37:56', '2021-03-24 23:32:46'),
('61ab73c8-bc9d-4c39-9c99-03772e0eb960', 'Quần thụng', 'QT1', 0, 12, 25000, 26000, 1, 1, NULL, NULL, NULL, NULL, 'quan', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-24 10:37:26', '2021-03-25 13:56:36'),
('6906316a-529a-4244-afba-958f2a729c11', 'Áo mưa ( xanh )', 'AM1-XA1', 1, NULL, 550000, 605000, NULL, NULL, NULL, NULL, 'xanh', 256, 'Áo mưa--> Áo mưa ( xanh )', '5e024ca3-a4f5-46ea-9757-701bce8dded7', 'vtt', '2021-03-25 14:24:06', '2021-03-25 14:43:35'),
('69a762bd-0149-41da-9566-685eb4d6b326', 'Quần ( đen )', 'Q6-DE', 1, NULL, 300000, 400000, NULL, NULL, NULL, NULL, 'đen', NULL, 'Quần--> Quần ( đen )', 'f7e47423-0e11-4f93-9788-c33fb4c4dc37', 'vtt', '2021-03-24 22:51:39', '2021-03-24 22:55:20'),
('6d705f7c-4633-4cc0-970c-1b343470f56a', 'Giày', 'G8', 1, 4, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, 'Giày', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-23 22:02:50', '2021-03-23 22:02:50'),
('7623d42f-35f4-1ce5-987d-e8c757976496', 'Xe máy', 'XM2', 0, 14, 3815037, 60000000, 1, 1, 'Quis voluptas mollitia fuga qui. Quasi molestiae est assumenda vero. Sed consequatur nesciunt alias neque. Perspiciatis magni sit eaque hic. Voluptate id itaque nemo quia; unde doloribus sed laudantium repudiandae. Aspernatur et dolores ad et? Corporis eius natus voluptates eum. Et sit quidem molestiae veniam. Praesentium cupiditate qui eveniet ut.\r\n', 'QJG099D79P747Y00T217LY27NO02E3WI5741', 'LavenderPurple', 92549623, 'Xe máy--> Xe máy', '5ae2d70b-201d-3e23-7f32-6a1673ffca7c', 'Myles Angel', '2019-09-06 15:11:02', '2021-03-24 21:07:45'),
('76c270a8-bf96-4162-8fbe-f4a171cb5ec1', 'Áo', 'A3', 1, 15, 500000, 600000, 2, 1, 'test them moi nhieu ban ghi 1', 'string', 'string', 1886, 'Áo', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 20:36:54', '2021-03-25 11:32:32'),
('7d5e0235-514c-4b4f-8d54-92aa39392123', 'Chổi lau nhà ( đỏ )', 'CLN1-DE1', 1, NULL, 30000, 40000, NULL, NULL, NULL, NULL, 'đỏ', NULL, 'Chổi lau nhà--> Chổi lau nhà ( đỏ )', '18159baf-9feb-4f52-a10f-77ec4e37abd5', 'vtt', '2021-03-25 13:40:08', '2021-03-25 13:40:08'),
('811cc4b9-201d-4204-b7ac-187e197941f1', 'Áo ( xanh )', 'A3X1', 1, NULL, 500000, 600000, NULL, NULL, NULL, NULL, 'xanh', NULL, 'Áo--> Áo ( xanh )', '76c270a8-bf96-4162-8fbe-f4a171cb5ec1', 'vtt', '2021-03-24 22:22:55', '2021-03-25 11:32:33'),
('821a9e03-43b0-4d0c-af99-1bbf05a4012b', 'Áo', 'A8', 1, 15, 500000, 600000, 2, 1, 'test them moi nhieu ban ghi 2', 'string', 'string', NULL, 'Áo', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-25 08:04:20', '2021-03-25 08:04:20'),
('83f54006-2758-440c-85e6-a86faa47440a', 'Áo', 'A2', 1, 15, 500000, 600000, 2, 1, 'test them moi nhieu ban ghi 2', 'string', 'string', 1887, 'Áo', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 20:37:01', '2021-03-25 08:09:24'),
('8aae9cc1-e1b0-45dc-abe9-1ee4f126f193', 'Đồ dùng cá nhân', 'DDCN5', 1, 1, 338493263, 240000, 1, 0, 'Animi minus architecto soluta accusamus dolore fugit dolore sunt quod. Veritatis eaque sit fugiat similique. Natus asperiores omnis ratione et blanditiis officiis id accusantium ducimus minima doloremque labore dicta consequatur. Quo distinctio et labore voluptates; dicta temporibus et quaerat et. Maxime iusto sed excepturi error; sed fuga animi voluptatem non.', '4M46S3B', NULL, NULL, 'Đồ dùng cá nhân', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-24 08:02:48', '2021-03-24 08:02:48'),
('8bf2d794-66cd-45f1-bbe4-1ad692702937', 'giày', 'G9', 1, 4, 50000, 60000, 1, 1, NULL, NULL, NULL, NULL, 'giày', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-23 22:17:00', '2021-03-24 08:13:59'),
('936a202a-b69f-4e3e-9431-a7305deb7f72', 'xoong', 'X1', 0, 2, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, 'xoong', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-24 10:53:16', '2021-03-24 14:28:24'),
('a5d43b5b-ee43-4c74-873e-92ff8986f152', 'quần', 'Q5', 0, 12, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, 'quần', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-24 14:25:49', '2021-03-24 22:59:23'),
('a7f2f7b5-c97c-408a-9353-6f4b721b3cf7', 'Quần', 'Q7', 1, 1, 20000, 20000, 3, 1, NULL, NULL, NULL, NULL, 'quan', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-24 10:45:35', '2021-03-25 11:34:13'),
('ad70fa65-9e85-4d34-aed4-61d1246f6a9a', 'Áo mưa', 'AM2', 1, 15, 500000, 600000, 2, 1, 'string', 'string', 'string', NULL, 'Áo mưa', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 11:09:34', '2021-03-23 16:32:32'),
('b1ff77bb-1304-4fa0-afa5-45d6de1ea5d1', 'Xe Cub', 'XC1', 1, 14, 9000000, 10000000, 2, 1, 'Xe trẻ trâu', NULL, NULL, NULL, 'Xe Cub', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 20:49:39', '2021-03-22 20:49:39'),
('b4325727-31a6-41ce-aaa7-2de9484bb919', 'Chổi lau nhà ( đen )', 'CLN1-DO1', 1, NULL, 30000, 40000, NULL, NULL, NULL, NULL, 'đen', NULL, 'Chổi lau nhà--> Chổi lau nhà ( đen )', '18159baf-9feb-4f52-a10f-77ec4e37abd5', 'vtt', '2021-03-25 13:40:08', '2021-03-25 13:40:08'),
('b47538f1-0ad0-4f38-b23e-303976a519af', 'Giày  ( đen )', 'G10-DE1', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'đen', NULL, 'Giày --> Giày  ( đen )', '2e9c2d0c-d90d-49b8-a4a0-f959972f9e9f', 'vtt', '2021-03-25 09:08:31', '2021-03-25 09:08:31'),
('b7f41864-cf21-4599-8518-796035b7df62', 'Quả mận', 'QM1', 1, 9, 15000, 20000, 3, 1, 'Mận Trung Quốc', NULL, NULL, NULL, 'Quả mận', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 09:12:31', '2021-03-22 09:12:31'),
('b802f36c-d063-4059-ac74-2d186ebbea04', 'Áo lót nam', 'ALN5', 1, 15, 100000, 200000, 1, 1, 'Áo lót ren', NULL, NULL, NULL, 'Áo lót nữ', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 10:40:29', '2021-03-25 11:06:53'),
('b9e98da2-4686-4946-ad54-87774a97c35a', 'Xe máy Honda 2', 'XMH2', 1, 14, 90000000, 150000000, 1, 1, 'Xe máy đắt tiền cho nhà giàu Test thêm mới', 'link:///', 'Đỏ', 170210412, 'Xe máy--> Xe máy--> Xe máy Honda 2', '7623d42f-35f4-1ce5-987d-e8c757976496', 'vtt', '2021-03-24 21:08:39', '2021-03-24 21:08:39'),
('bd0b525c-738c-407a-b128-a0a8079dd12d', 'Áo', 'A4', 1, 15, 500000, 600000, 2, 1, 'test them moi nhieu ban ghi 1', 'string', 'string', NULL, 'Áo', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-23 17:36:50', '2021-03-23 17:36:50'),
('bf8e3d2e-a726-4f4d-bd49-b543016d46c2', 'quần ( đen )', 'Q5-DE', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'đen', NULL, 'quần--> quần ( đen )', 'a5d43b5b-ee43-4c74-873e-92ff8986f152', 'vtt', '2021-03-24 22:59:23', '2021-03-24 22:59:23'),
('bfe1db84-6053-4b7b-8193-699843fb128c', 'Đồng hồ Rolex', 'DHR2', 1, 3, 200000000, 250000000, 2, 0, 'Đồng hồ cho nhà giàu vkl', NULL, NULL, NULL, 'Đồng hồ Rolex', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 20:48:00', '2021-03-22 20:48:00'),
('cb3f9c60-dafb-46cc-8db9-eb841eebc8f4', 'Quạt Điện', 'QĐ1', 1, 2, 500000, 550000, 2, 1, 'Quạt', NULL, NULL, NULL, 'Quạt Điện', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-21 20:47:00', '2021-03-21 20:47:00'),
('cf196485-5b04-4881-a051-2939586ee3ae', 'Quần thụng ( đen )', 'QT1-DE1', NULL, NULL, 25000, 26000, NULL, NULL, NULL, NULL, 'đen', NULL, 'Quần thụng--> Quần thụng ( đen )', '61ab73c8-bc9d-4c39-9c99-03772e0eb960', 'vtt', '2021-03-25 13:56:36', '2021-03-25 13:56:36'),
('d3cf2496-78a2-4853-932e-d2b53f0a4398', 'Áo lót nữ', 'ALN3', 1, 15, 100000, 200000, 1, 1, 'Áo lót ren', NULL, NULL, NULL, 'Áo lót nữ', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-20 12:36:06', '2021-03-23 16:32:41'),
('d40cd4dc-a807-446a-b0a0-fed60ea0366d', 'Quần thụng ( tím )', 'QT1-TI1', NULL, NULL, 25000, 26000, NULL, NULL, NULL, NULL, 'tím', NULL, 'Quần thụng--> Quần thụng ( tím )', '61ab73c8-bc9d-4c39-9c99-03772e0eb960', 'vtt', '2021-03-25 13:56:36', '2021-03-25 13:56:36'),
('d768b114-3334-401f-8673-3927f99d51ce', 'áo mưa  ( đen )', 'AM3-DEN', 1, 15, 2000, 5000, NULL, 1, NULL, NULL, 'đen', NULL, 'áo mưa --> áo mưa  ( đen )', '52d303b9-e475-4246-9d6d-2a0f6bc3d3f9', 'vtt', '2021-03-23 22:03:45', '2021-03-23 22:03:45'),
('e1066cda-22f3-4d5b-85fe-0c16d92f7724', 'Áo lót nam ( đen )', 'ALN5-DE1', 1, NULL, 100000, 200000, NULL, NULL, NULL, NULL, 'đen', NULL, 'Áo lót nam--> Áo lót nam ( đen )', 'b802f36c-d063-4059-ac74-2d186ebbea04', 'vtt', '2021-03-25 11:06:53', '2021-03-25 11:06:53'),
('e1fbf8c8-598b-461c-b308-381c86c94d6a', 'Giày Vans', 'GV1', 1, 7, 200000, 300000, 1, 1, 'Giày nhu bòi', NULL, NULL, NULL, 'Giày Vans', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-23 21:48:45', '2021-03-23 21:48:45'),
('e6bed2d3-67c8-46ac-a9b4-45c905a57b8d', 'Giày', 'G7', 1, 4, 2000000, 3000000, 2, 1, NULL, NULL, NULL, NULL, 'Giày', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-23 22:01:09', '2021-03-23 22:01:09'),
('ed33fab3-222e-4740-8d49-16e971249e88', 'áo ( hồng )', 'A7-HO1', 0, NULL, 300000, 400000, NULL, NULL, NULL, NULL, 'hồng', NULL, 'áo--> áo ( hồng )', '551a2660-e828-4a65-8a38-425eb2467bda', 'vtt', '2021-03-25 09:11:16', '2021-03-25 11:29:45'),
('efcbe919-7549-48aa-924b-a42cbfb65632', 'Áo mưa người lớn', 'AMNL1', 1, 15, 35000, 45000, 2, 1, 'Áo mưa cỡ lớn', NULL, NULL, NULL, 'Áo mưa người lớn', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-21 14:47:21', '2021-03-21 14:47:21'),
('f1e34bbc-e0fa-4846-bb40-eae56f20ade1', 'Giày da đen ( đen )', 'GDD1-DE1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'đen', NULL, 'Giày da đen--> Giày da đen ( đen )', '25073210-2818-4817-944f-418970898609', 'vtt', '2021-03-25 09:33:48', '2021-03-25 09:34:20'),
('f34fb611-3f69-4adc-8933-86a40ca610c3', 'Bata Trắng', 'BT2', 1, 8, 70000, 90000, 1, 1, 'Không có', NULL, NULL, NULL, 'Bata Trắng', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-22 14:16:28', '2021-03-22 14:16:28'),
('f7e47423-0e11-4f93-9788-c33fb4c4dc37', 'Quần', 'Q6', 0, 12, 300000, 400000, 2, 1, 'test thêm mới', NULL, NULL, NULL, 'Quần', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-24 22:51:39', '2021-03-24 22:55:20'),
('f7f5327e-a517-4010-8a45-7b54802cc70f', 'Giày Yeezy 700', 'GY1', 1, 7, 700000, 1000000, 1, 1, 'Giày đắt vcl', NULL, NULL, NULL, 'Giày Yeezy 700', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-20 16:49:38', '2021-03-20 16:49:38'),
('f97d802c-a0ae-451a-94c5-190f76b22ae7', 'Áo ', 'A1', 1, 15, 500000, 600000, 2, 1, 'test them moi nhieu ban ghi 2', 'string', 'string', NULL, 'Áo ', '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-23 08:46:32', '2021-03-23 08:46:32');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;